# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OSMroutingPT
                                 A QGIS plugin
 It create the Public Transports path for each PT with a CSV table with stops sequence and coordinate
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-05
        copyright            : (C) 2024 by Luigi Dal B./FlowRide
        email                : luigi.dalbosco@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OSMroutingPT class from file OSMroutingPT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OSM_PT_routing import OSMroutingPT
    return OSMroutingPT(iface)
